spring.application.name=auth-service

server.port=4005

#spring.datasource.url=jdbc:postgresql://localhost:5432/auth_service
#spring.datasource.username=postgres
#spring.datasource.password=kamal1964
#spring.jpa.hibernate.ddl-auto=create
#spring.sql.init.mode=always
#JWT_SECRET=he38bWpzBqaTLjaKMCQI+0UVQ6wWLbfXBr5RrSuBOtGFudLe1HltI/geo+9k7+LuQBRiqIaIlcmuT1TEI+m9Tw==