services:
  billing-service:
    container_name: billing-service
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    image: billing-service:latest
    ports:
      - "4001:4001" #REST port
      - "9001:9001" #gRPC port
    environment:
      - GRPC_SERVER_PORT=9001
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal-network

  patient-service:
    container_name: patient-service
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    image: patient-service:latest
    environment:
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001

        # Database variables
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - billing-service
      - patient-service-db
      - kafka

    networks:
      - internal-network

  patient-service-db:
    container_name: patient-service-db
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
    ports:
      - "5000:5432"
    volumes:
      - C:/Users/User/db_volumes/patient-service-db:/var/lib/postgresql/data
    networks:
      - internal-network

  analytics-service:
    container_name: analytics-service
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    image: analytics-service:latest
    ports:
      - "4002:4002"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    ports:
      - "4004:4004"
    networks:
      - internal-network

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    ports:
      - "4005:4005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
    networks:
      - internal-network

  auth-service-db:
    container_name: auth-service-db
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
    ports:
      - "5001:5432"
    volumes:
      - C:/Users/User/db_volumes/auth-service-db:/var/lib/postgresql/data
    networks:
      - internal-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"   # For Containers
      - "9093:9093"   # Controller port
      - "9094:9094"   # For host machine connection (EXTERNAL)
    environment:
      # -----------------------------
      # KRaft (Kafka without Zookeeper)
      # -----------------------------
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # -----------------------------
      # Listener settings
      # -----------------------------
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094  # Hostdan qoşulmaq üçün
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT

      # -----------------------------
      # Metadata + logs
      # -----------------------------
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: "wK1vN2a4QjS1e8FZtVh3kA=="   # Random ID, it should not be changed

      # -----------------------------
      # Single node config
      # -----------------------------
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge  # optional, this is the Docker's default network ddriver type