### Updates a patient
PUT http://lb-2f7bf879.elb.localhost.localstack.cloud:4004/api/patients/4ff9e83d-2cd0-445d-8481-4d34beb7b23d
Content-Type: application/json

{
  "name": "Kamal Shabanov updated",
  "email": "kamalshabano@example.com",
  "address": "baki",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2004-03-03"
}